export const circleTextContent = "li:last-child p";
export const circleChanging = "[class*=circle_changing]";
export const circleDefault = "[class*=circle_default]";
export const circleModified = "[class*=circle_modified]";
export const circleTail = "[class*=circle_tail]";
export const circleHead = "[class*=circle_head]";
export const circleLetter = "[class*=circle_letter]";
export const circleIndex = "[class*=circle_index]";
export const lastCircle = "li:last-child";
export const firstCircle = "li:first-child";
export const circle = "li";
export const circleContainer = "ul";
export const input = "input";
export const inputValue = 'input[name="Введите значение"]';
export const inputIndex = 'input[name="Введите индекс"]';
export const addButton = "Добавить";
export const removeButton = "Удалить";
